### ISSUE TITLE
Console not opening in my local machine

### ISSUE THREAD

**Issue by jplreddy** [wearefrank/frank-runner#90]
Hi Team,

Tomcat is started but while opening the console getting below error. please do the the needful on priority.
12-Apr-2024 12:54:05.364 WARNING [main] org.apache.catalina.core.StandardServer.await Invalid shutdown command [GET / HTTP/1.1] received
12-Apr-2024 12:54:07.998 WARNING [main] org.apache.catalina.core.StandardServer.await Invalid shutdown command [] received
12-Apr-2024 12:54:08.006 WARNING [main] org.apache.catalina.core.StandardServer.await Invalid shutdown command [] received

**Comment by jacodg** [comment]
Hi jplreddy, this is probably because you try to access the server port with a brouser. You should use a different port in your browser (see my last comment on https://github.com/wearefrank/frank-runner/issues/87)

P.s. the Frank!Runner will print the url you can use at the end of the output in the console (below the ASCII art log)
